# database.py — SQLAlchemy setup (auto-generated by VIA)
import os
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

# Reads DATABASE_URL set by Render's PostgreSQL service
# Falls back to local SQLite for development
GROQ_MODEL = os.getenv("GROQ_MODEL", "qwen/qwen3.8-27b")
DATABASE_URL = (
    os.getenv("DATABASE_URL")
    or os.getenv("RENDER_DATABASE_URL")
    or "sqlite:///./app.db"
)

# Render injects postgres:// but SQLAlchemy 1.4+ requires postgresql://
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)

# Validate the URL has no placeholder values
if ":port" in DATABASE_URL or "@host:" in DATABASE_URL or "user:password" in DATABASE_URL:
    # Fallback to SQLite if URL looks like a template placeholder
    import logging as _dblog
    _dblog.getLogger("via").warning("DATABASE_URL appears to be a placeholder — falling back to SQLite")
    DATABASE_URL = "sqlite:///./app.db"

# SQLite needs check_same_thread=False; PostgreSQL does not
connect_args = {"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {}

engine = create_engine(DATABASE_URL, connect_args=connect_args)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
